import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E Commerce",
  description: "Generated by Mkae create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col w-screen justify-center items-center">
          <Header />
          <div className=" w-[1170px]"> {children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
